version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: french_app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/french_app_development
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    command: >
      bash -c "
        bundle install &&
        rails db:create db:migrate db:seed &&
        rails server -b 0.0.0.0
      "

volumes:
  postgres_data:
  redis_data:
  bundle_cache: 